export type View =
  | "dashboard"
  | "job-board"
  | "resumes"
  | "ats"
  | "copilot"
  | "agents"
  | "mail"
  | "calendar"
  | "interviews"
  | "reports"
  | "ai-usage"
  | "vendor-monitor"
  | "firebase"
  | "bid-management"
  | "settings";
